// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaErJ9BgcGQsfw_8cdfbuG9YnOtf4_0Oo',
    appId: '1:271197345084:web:654be44e4da2777854ba39',
    messagingSenderId: '271197345084',
    projectId: 'withon-app',
    authDomain: 'withon-app.firebaseapp.com',
    storageBucket: 'withon-app.firebasestorage.app',
    measurementId: 'G-Z228JW2QG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxnPmSaVT6PIOTU_J8aZq82fFeEGl30cY',
    appId: '1:271197345084:android:9af768bbbe25621054ba39',
    messagingSenderId: '271197345084',
    projectId: 'withon-app',
    storageBucket: 'withon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABGqPk4CSumk9tvZJ-ltAZ9wxmOFUeiac',
    appId: '1:271197345084:ios:7edb8a66f235f75254ba39',
    messagingSenderId: '271197345084',
    projectId: 'withon-app',
    storageBucket: 'withon-app.firebasestorage.app',
    iosBundleId: 'com.example.withonProjects',
  );
}
